### ISSUE TITLE
[Q]  How To Test This App

### ISSUE THREAD

**Issue by Lukada-taiya** [ncosd/food-pantry-app#280]
# Topic:

# Question:
I am interested in contributing to this project, if that's ok. I have replicated it to my local machine. But how do I create an admin account? I used the login page to create an account but it requires another account to grant me access. How do I move from there to explore the different parts of the application?

**Comment by dherbst** [comment]
Hi @Lukada-taiya,

If you are running with the datastore emulator in the `admin` site, the account `user@example.com` is an admin when you login with that account.   You can use that to `approve` your newly created account.

If you want to add the `admin` custom claim to the account in the authentication emulator, once it is running, go to http://localhost:4000/ then click on `go to auth emulator`
![image](https://github.com/ncosd/food-pantry-app/assets/136589/6ed13ca7-1ab6-4e14-8031-6a93e18ec262)

Click on the three dots for the user you want to edit, and click `edit user`
![image](https://github.com/ncosd/food-pantry-app/assets/136589/e67e1ec3-f768-4e66-a513-1e72e39222da)

Then, in the `custom claims` add `admin: true`

![image](https://github.com/ncosd/food-pantry-app/assets/136589/e22bdb16-676a-47d7-ae03-4ba870c87561)

Separately, you are running with the cloud firestore, there is a script to add the custom claim, because it cannot be added in the console.  It is in the `web/functions/scripts/` directory, named `setadmin.js`.  There are instructions in the `readme` there on how to run that script.
